export const types = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CART_ITEMS: "SET_CART_ITEM",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  INCREASE_QUANT: "INCREASE_QUANT",
  DECREASE_QUANT: "DECREASE_QUANT",
  GET_TOTALS: "GET_TOTALS",
  CLEAR_CART: "CLEAR_CART"
}